apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: main-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/namhh5820/k-helm-charts.git
  ref:
    branch: main
